# Disable CI triggers, we don't want a build per merge to Master
trigger: none

resources:
  containers:
  - container: RhelContainer
    image: microsoft/dotnet-buildtools-prereqs:rhel7_prereqs_2

# phases:
#   - template: /eng/corefx-steps.yml
#     parameters:
#       name: Linux
#       queue:
#         container: RhelContainer
#         name: Hosted Ubuntu 1604
#         matrix:
#           x64_Release:
#             _configuration: Release
#             _archGroup: x64
#       framework: netcoreapp
#       targetOS: Linux
#       helixTargetQueues: Centos.74.Amd64.Open;RedHat.74.Amd64.Open;Debian.87.Amd64.Open;Ubuntu.1404.Amd64.Open;Ubuntu.1604.Amd64.Open;Ubuntu.1804.Amd64.Open;OpenSuse.423.Amd64.Open;Fedora.27.Amd64.Open

#   - template: /eng/corefx-steps.yml
#     parameters:
#       name: Windows
#       queue:
#         name: dotnet-external-temp
#         matrix:
#           x64_Debug:
#             _configuration: Debug
#             _archGroup: x64
#           x86_Release:
#             _configuration: Release
#             _archGroup: x86
#       framework: netcoreapp
#       targetOS: Windows_NT
#       helixTargetQueues: Windows.7.Amd64.Open;Windows.81.Amd64.Open;Windows.10.Amd64.ClientRS4.ES.Open

jobs:
  - job: DefaultMatrix
    displayName: Build
    strategy:
      maxParallel: 99
      matrix:
        Windows_x64_Debug:
          _configuration: Debug
          _archGroup: x64
          _targetOS: Windows_NT
          _framework: netcoreapp
          _helixTargetQueues: Windows.7.Amd64.Open;Windows.81.Amd64.Open;Windows.10.Amd64.ClientRS4.ES.Open
    steps:
      - template: /eng/corefx-steps.yml
        parameters:
          name: Windows
          queue:
            name: dotnet-external-temp
          framework: $(_framework)
          targetOS: $(_targetOS)
          helixTargetQueues: $(_helixTargetQueues)