# Disable CI triggers, we don't want a build per merge to Master
trigger: none

resources:
  containers:
  - container: RhelContainer
    image: microsoft/dotnet-buildtools-prereqs:rhel7_prereqs_2

phases:
  - template: /eng/corefx-steps.yml
    parameters:
      name: Linux x64 Release
      queue:
        container: RhelContainer
        name: Hosted Ubuntu 1604
        matrix:
          x64_Release:
            _configuration: Release
            _archGroup: x64
      framework: netcoreapp
      targetOS: Linux
      helixTargetQueues: Centos.74.Amd64.Open;RedHat.74.Amd64.Open;Debian.87.Amd64.Open;Ubuntu.1404.Amd64.Open;Ubuntu.1604.Amd64.Open;Ubuntu.1804.Amd64.Open;OpenSuse.423.Amd64.Open;Fedora.27.Amd64.Open
