parameters:
  name: ''
  pool: {}
  strategy: {}
  submitToHelix: true
  testOuterloop: false
  skipTests: true
  runtimeOS: ''
  targetOS: ''

jobs:
  - job: ${{ parameters.name }}
    variables:
      _targetOSParam: /p:TargetOS=$(targetOS)

      ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: build.cmd
        _msbuildCommand: powershell -ExecutionPolicy ByPass -NoProfile eng\common\msbuild.ps1 -warnaserror:0
        _buildCommonArgs: -ci
      ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: ./build.sh
        _msbuildCommand: ./eng/common/msbuild.sh --warnaserror false
        _buildCommonArgs: --ci

      ${{ if eq(parameters.runtimeOS, '') }}:
        _runtimeOSParam: ''
      ${{ if ne(parameters.runtimeOS, '') }}:
        _runtimeOSParam: /p:RuntimeOS=${{ parameters.runtimeOS }}

      ${{ if ne(parameters.submitToHelix, 'true') }}:
        _archiveTests: false
      ${{ if eq(parameters.submitToHelix, 'true') }}:
        _helixToken: $(BotAccount-dotnet-github-anon-kaonashi-bot-helix-token)
        _archiveTests: true
        _sendToHelixArgs: eng/sendtohelix.proj /t:test /p:HelixAccessToken=$(_helixToken) /p:\"HelixTargetQueues=$(helixTargetQueues)\" /p:HelixBuild=$(Build.BuildNumber).${{ parameters.name }} $(_targetOSParam)

    pool:
      ${{ insert }}: ${{ parameters.pool }}
    strategy:
      ${{ insert }}: ${{ parameters.strategy }}
    steps:
      - script: $(_buildScript)
                $(_buildCommonArgs)
                -includetests
                -framework $(framework)
                $(_runtimeOSParam)
                /p:ArchGroup=$(_archGroup)
                /p:ConfigurationGroup=$(_configuration)
                /p:SkipTests=${{ parameters.skipTests }}
                /p:ArchiveTests=$(_archiveTests)
        displayName: Build Sources and Tests
      - ${{ if eq(parameters.submitToHelix, 'true') }}:
          - script: $(_msbuildCommand)
                    src/upload-tests.proj
                    /t:CompressRuntimeDir
                    /p:ArchGroup=$(_archGroup)
                    /p:ConfigurationGroup=$(_configuration)
                    $(_targetOSParam)
            displayName: Compress Runtime Directory
          - script: $(_msbuildCommand) $(_sendToHelixArgs)
            displayName: Send to Helix