parameters:
  name: ''
  pool: {}
  strategy: {}
  skipTests: true
  targetOS: ''
  testOuterloop: false
  container: ''
  buildScriptPrefix: ''
  submitToHelix: true

jobs:
  - job: ${{ parameters.name }}
    variables:
      # OS Specific commands
      ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: build.cmd
        _msbuildCommand: powershell -ExecutionPolicy ByPass -NoProfile eng\common\msbuild.ps1 -warnaserror:0 -ci
      ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: ./build.sh
        _msbuildCommand: ./eng/common/msbuild.sh --warnaserror false --ci

    pool:
      ${{ insert }}: ${{ parameters.pool }}
    strategy:
      maxParallel: 99
      ${{ insert }}: ${{ parameters.strategy }}

    container: ${{ parameters.container }}

    steps:
      - script: $(_buildScript)
              $(_buildCommonArgs)
              -includetests
              -framework $(framework)
              /p:ArchGroup=$(_archGroup)
              /p:ConfigurationGroup=$(_configuration)
              /p:SkipTests=${{ parameters.skipTests }}
              /p:ArchiveTests=$(submitToHelix)
              /p:Outerloop=${{ parameters.testOuterloop }}
              ${{ parameters.buildExtraArguments }}
        displayName: Build Sources and Tests
      
      - ${{ if eq(parameters.submitToHelix, 'true') }}:
        - template: /eng/pipelines/helix.yml
          parameters:
            targetOS: ${{ paremeters.targetOS }}
            archGroup: $(archGroup)
            configuration: $(configuration)
            helixQueues: $(helixQueues)
            msbuildScript: $(_msbuildCommand)
            framework: $(framework)
